name: helpusmall
description: Indicação de produtos.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  provider: ^4.1.2
  flutter_spinkit: ^4.1.2+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/background-image.png
    - images/logo-azul.png
    - images/icon-localizacao.png

  fonts:
  - family: Cocogoose
    fonts:
    - asset: fonts/Cocogoose-Pro-Light-trial.ttf